### ISSUE TITLE
New beaches todo

### ISSUE THREAD

**Issue by Soro335** [FrozenBlock/WilderWild#103]
- [ ] Remove beach generation near cave entrances
- [ ] Figure out how to make them only generate within proximity to water
- [ ]  Add sandstone generation under the sand
- [ ] Add more biomes for beach generation

**Comment by BluePhoenixLOL** [comment]
beaches dont have sandstone, thats deserts

**Comment by MerpisMe** [comment]
> beaches dont have sandstone, thats deserts

yeah real life beaches have mud so lets add mud under them :trollface:

**Comment by BluePhoenixLOL** [comment]
beaches have crabs lets add crabs
