### ISSUE TITLE
1.1 Todo

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/WilderWild#106]
- [x] Add Presence Footsteps compatibility for newer blocks
- [x] #139 
- [x] #151
- [x] Finalize Cabins and don't associate them with jellyfish caves
- [x] Finish Abandoned Cabin Loot Tables
- [x] Play "start" sounds when starting to use Copper Horns
- [x] Implement keyframe-based Allay dance animation
- [x] Make non-worldgen sculk slab/stair/wall spreading only work on the non-worldgen tags for them
- [x] Loot Tables For All Jellyfish Colors
- [x] Possibly multiple colors of Mesoglea
- [x] Final Mesoglea textures
- [x] Possibly make Turtles attack Jellyfish(?)
- [x] Add missing copper horn recipes
- [x] Stop hanging tendrils from generating with sensors/shriekers two blocks above

**Comment by AViewFromTheTop** [comment]
@Treetrain1 @MerpisMe @BluePhoenixLOL this is how the outpost loot tables do it

    {
      "bonus_rolls": 0,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:goat_horn"
        }
      ],
      "functions": [
        {
          "function": "minecraft:set_instrument",
          "options": "#minecraft:regular_goat_horns"
        }
      ],
      "rolls": {
        "type": "minecraft:uniform",
        "max": 1,
        "min": 0
      }
    }

**Comment by AViewFromTheTop** [comment]
pinning this since literally nobody wants to look at it

**Comment by MerpisMe** [comment]
> -Possibly make Turtles attack Jellyfish(?)

i approve of this

**Comment by Treetrain1** [comment]
is any of this already done?

**Comment by MerpisMe** [comment]
> is any of this already done?

no

**Comment by Treetrain1** [comment]
We also need to figure out how to make the config option for beta beaches work.
Right now, they generate regardless of what you have set for the option

**Comment by AViewFromTheTop** [comment]
> We also need to figure out how to make the config option for beta beaches work. Right now, they generate regardless of what you have set for the option

we just need a new config system

**Comment by MerpisMe** [comment]
> * [ ]  Make Jellyfish Caves Much Less Common, generate under ocean biomes, and be much smaller on average

@AlexTheDolphin0

**Comment by MerpisMe** [comment]
> - [ ] Make non-worldgen sculk slab/stair/wall spreading only work on the non-worldgen tags for them

@Treetrain1 would you be able to do this?

**Comment by Treetrain1** [comment]
> > * [ ]  Make non-worldgen sculk slab/stair/wall spreading only work on the non-worldgen tags for them
> 
> @Treetrain1 would you be able to do this?

yeah probably
is there already a tag for me to use?

**Comment by AViewFromTheTop** [comment]
have the new copper horn recipes been added
if so, i honestly think we're good to go
I can't find a way to do the start sound for loops, either

**Comment by Treetrain1** [comment]
> have the new copper horn recipes been added
> if so, i honestly think we're good to go
> I can't find a way to do the start sound for loops, either

Beta beach config? :trollface:

**Comment by MerpisMe** [comment]
> * [ ] Implement keyframe-based Allay dance animation

@Treetrain1 i know you know how to do this
you literally just need to have it play the keyframe animation when it's dancing. i can worry about overriding the math based dance animation, just at the very least set it up for me if you could please

**Comment by MerpisMe** [comment]
also yes the animation itself is already in the code

**Comment by AViewFromTheTop** [comment]
@MerpisMe Shall you do the honours?

**Comment by MerpisMe** [comment]
> @MerpisMe Shall you do the honours?

no i have to add one thing to it

**Comment by MerpisMe** [comment]
k added
whenever you have time to take care of that last one, please do so

**Comment by AViewFromTheTop** [comment]
> k added whenever you have time to take care of that last one, please do so

shoot i forgot about that
thanks for reminding me

**Comment by AViewFromTheTop** [comment]
not sure if i'll be able to finish it because i have a.r.t. in like 20 mins im nervous

**Comment by MerpisMe** [comment]
BTW
apparently architectury has an API to allow us to make the mod work on both forge and fabric
@Treetrain1 would you mind looking into that?

**Comment by AViewFromTheTop** [comment]
meh i think that'd be too janky and too much of a change for us
having a specific person/team working on a separate forge version would be much less stressful and a lot easier imo

**Comment by MerpisMe** [comment]
> meh i think that'd be too janky and too much of a change for us

i'm pretty sure it only requires very minimal actual code changes
also forge and fabric are actually extremely similar. like 90% of the differences between the two are the names of the methods and exactly how they work, but for the most part a lot of stuff does the same thing 
> having a specific person/team working on a separate forge version would be much less stressful and a lot easier imo

not really. we'd have to either worry about updating changes we make to the fabric version every time we make them, or go back and *manually* port everything over once we finish the update. that's stupid tedious.

**Comment by AViewFromTheTop** [comment]
idk anything about forge
the only thing i know is that each time i've tried to do something on there, it just won't work

**Comment by AViewFromTheTop** [comment]
and i have no idea what architectury implies, or the new incompatibilities that'll introduce

**Comment by AViewFromTheTop** [comment]
also i found the problem for the last one
i'm 99% sure treetrain made the mixin inject after the block was already placed

**Comment by AViewFromTheTop** [comment]
yep

**Comment by AViewFromTheTop** [comment]
> also i found the problem for the last one i'm 99% sure treetrain made the mixin inject after the block was already placed

@Treetrain1 can you fix this i got something going on and i gtg

**Comment by MerpisMe** [comment]
he's at school and isnt allowed to be on his phone at all during the day

**Comment by Soro335** [comment]
can weee, yeah
![image (1)](https://user-images.githubusercontent.com/82042293/192356759-b3d7f6dd-761d-47ce-bfca-76cac908fa5b.png)
![image](https://user-images.githubusercontent.com/82042293/192356771-9599ee3d-4020-449c-bbac-2473a1f8a934.png)

**Comment by MerpisMe** [comment]
if we could sort stuff in the creative inventory without it being a hassle then i would love to
i feel like there's gotta be some kind of mixin for that or something
like you specify what two items you'd like to insert the stuff between and it'd put them there

**Comment by MerpisMe** [comment]
ok update on the architectury thing: it only requires us to change a few registry things, everything else is handled automatically.
it supposedly works really well. mixins and everything work.
the only thing we'd have to do is apply architectury to frozenlib as well so it also works on forge. we'd also have to pull from the forge ports of any other api mods we use

**Comment by MerpisMe** [comment]
cloth config is built on architectury, so it works on both forge and fabric

**Comment by AViewFromTheTop** [comment]
idk i'm still skeptical

**Comment by MerpisMe** [comment]
> idk i'm still skeptical

it's made by the same guy that made cloth config if that makes you less skeptical

**Comment by AViewFromTheTop** [comment]
> it's made by the same guy that made cloth config if that makes you less skeptical

ok but how are we gonna use those other dependencies and all that w/ forge

copper pipes isn't on forge either, but this mod has stuff for it

**Comment by MerpisMe** [comment]
> ok but how are we gonna use those other dependencies and all that w/ forge

what dependencies do we even use? most of them should have forge ports

> copper pipes isn't on forge either, but this mod has stuff for it

you could just use architectury for it too

**Comment by MerpisMe** [comment]
architectury has forge ports of those built in i'm pretty sure (not sure about fabric asm but it probably says on [the architectury repo](https://github.com/shedaniel/Architectury)

**Comment by AViewFromTheTop** [comment]
ww would be SHIT without fabric-asm honestly

**Comment by MerpisMe** [comment]
> ww would be SHIT without fabric-asm honestly

what even is fabric asm

**Comment by AViewFromTheTop** [comment]
> what even is fabric asm

lets you add enums
it's the only way we have separate mobcaps for fireflies and jellyfish so they can actually spawn normally

**Comment by MerpisMe** [comment]
ok i just looked it up
forge has asm built in

**Comment by MerpisMe** [comment]
so it'll have a thing for that

**Comment by AViewFromTheTop** [comment]
> ok i just looked it up forge has asm built in

girl where tf did you find that i tried looking and didn't find anything

**Comment by AViewFromTheTop** [comment]
oh shit im an idiot you said forge, not architectury

**Comment by AViewFromTheTop** [comment]
either way, how in the world are we gonna access forge stuff for some parts and fabric stuff for others
i just don't get how that'll work

**Comment by MerpisMe** [comment]
yeah lol

**Comment by MerpisMe** [comment]
https://nekoyue.github.io/ForgeJavaDocs-NG/javadoc/1.18.2/net/minecraftforge/common/IExtensibleEnum.html

**Comment by AViewFromTheTop** [comment]
@MerpisMe it's restricted for me

**Comment by MerpisMe** [comment]
> @MerpisMe it's restricted for me

wtf

**Comment by AViewFromTheTop** [comment]
> wtf

yep
i told you i can't do much on the internet

**Comment by MerpisMe** [comment]
i hate your parents so much hahHaahAHA

**Comment by AViewFromTheTop** [comment]
ok i think the issue is that treetrain set growthstate to downstate in one part, but idk for sure

**Comment by AViewFromTheTop** [comment]
> ok i think the issue is that treetrain set growthstate to downstate in one part, but idk for sure

@MerpisMe yep that was the issue

**Comment by AViewFromTheTop** [comment]
May you do the honours?

**Comment by MerpisMe** [comment]
bingus

**Comment by AViewFromTheTop** [comment]
> bingus

WOOOOOOOOOOOOOO
wtf is a bingus but WOOOOOOOOOOOOO
LETS GO MEFI
