### ISSUE TITLE
TODO before first release

### ISSUE THREAD

**Issue by EthanRStokes** [FrozenBlock/WilderWild#59]
This issue contains everything we need to do before we release the first version of Wilder Wild. The rest of the bugs can probably(?) be fixed in a later update. I don't want to rush a release, but this is just the things we gotta get done lol

If there's anything else that I'm missing, please add it here.

GENERAL
---
- [x] Make a mod icon
- [x] Make a CurseForge page
- [x] France

BLOCKS
---
- [x] Fix missing and placeholder textures. This includes most of Cypress and a little bit of Baobab (i think baobab boats) #57 #50 
- [x] Hollowed Logs should not give an infinite source of water #51 
- [x] - Fix baobab sapling #65 

ENTITIES
---
- [x] Spawning Fireflies from /summon should not spawn an invisible firefly
- [x] Fix Ancient Horn projectile rendering

OTHER
---
- [x] Update the panorama so that Sculk Echoers don't exist lol.
- [x] (do this around the time of release) make a 『🌿』wilderwild or 『🌿』wilder-wild channel in the released mods category in the modding oasis
