### ISSUE TITLE
Merp's todo

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#7]
----
**TO-DO**
- [ ] Better looping angered Enderman sound (Should be more like soft static, still in the Ender realm though)
----
**ARCHIVE**
- [x] Fix remaining Copper Horn sounds
- [x] Make cattail hotdog things less rubbery
- [x] Improve White Dandelion Texture
- [x] Improve Milkweed Pod Texture
- [x] Roughen up echoer side texture
- [x] Make active echoer texture
- [x] Improve echoer sounds
- [x] Make echoer's model use more "round" numbers for part heights (10 instead of 11, 4 instead of 5, etc)
- [x] Make unique block sounds for ossein
- [x] Make unique block sounds for echoer
- [x] Make echoing sculk bubble particle
- [x] Make waterlily texture
- [x] Make shelf fungus models
- [x] Non-Horrific Termite Mound Texture
- [x] Animate hanging tendril
- [x] Make pollen block texture
- [x] Make hanging tendril wringing sounds
- [x] Ancient Horn texture
- [x] Ancient Horn Sound
- [x] Make Ancient Horn's reed use osseous sculk palette instead of gold palette
- [x] Improve Ancient Horn projectile texture
- [x] Unique Ancient Horn Vibration Dissipate (landing) sound
- [x] Add more Ancient Horn sound variants
- [x] Popping sounds for Big and normal echoing bubbles
- [x] Add root to lilypad model
- [x] Cracking sounds for Echo Glass
- [x] Healing sounds for Echo Glass
- [x] Better Echo Glass textures (cracking, possibly the entire block honestly)
- [x] red shelf fungus texture and model (new super mario brother)
- [x] Make unique warden death animation (and maybe get it to work in-game???)
- [x] Make unique sounds for breaking and walking on lilypads
- [x] Make sounds for mushrooms
- [x] Hollowed log sounds
- [x] Better temporary Milkweed texture
- [x] Termite Texture
- [x] Initial "burst" sound for Ancient Horn when you blow in it
- [x] Looping sound for Ancient Horn Projectile
- [x] Pick Up and Empty sounds for Firefly Bottles
- [x] Texture for stripped baobab, baboab boat, and baobab chest boat
- [x] Glory of The Snow Plant textures
- [x] Glory of The Snow Flower Lichen textures
- [x] Make cracks on Echo Glass less transparent so they can be seen easier
- [x] New Milkweed Textures - The one with pods needs to be worked on, that should at least change if the plant's shape doesn't change.

**Comment by MerpisMe** [comment]
@AViewFromTheTop appreciate the additions, i almost forgot about those two :trollface:

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop appreciate the additions, i almost forgot about those two :trollface:
![80CA6BD1-A0FB-42E5-A409-4B16D2BC8AAC](https://user-images.githubusercontent.com/87103914/164344377-32b6e0f1-0a43-41ab-9dc9-964da6ee1f01.jpeg)

**Comment by MerpisMe** [comment]
> ![80CA6BD1-A0FB-42E5-A409-4B16D2BC8AAC](https://user-images.githubusercontent.com/87103914/164344377-32b6e0f1-0a43-41ab-9dc9-964da6ee1f01.jpeg)

...come again?

**Comment by AViewFromTheTop** [comment]
> god please stop adding things for me to do im dying this is like 3 hours' worth of work gghhghhhhhhh

there's not really any rush to complete the tendril animation, the block was just created today
unless this is about the warden's album.... good luck with that.

**Comment by MerpisMe** [comment]
> there's not really any rush to complete the tendril animation, the block was just created today 

nah it's all good, i'm just not pacing *myself* well enough lol

**Comment by MerpisMe** [comment]
@AViewFromTheTop
![hanging_tendril_active](https://user-images.githubusercontent.com/27739930/164556349-d9066ba9-8cbf-41f0-b6fa-39d416b61c4d.gif)

**Comment by MerpisMe** [comment]
![image](https://user-images.githubusercontent.com/27739930/164560176-e9f1c979-ddc8-4060-86b2-515622e4c553.png)
![image](https://user-images.githubusercontent.com/27739930/164560194-785d57df-340e-473f-b430-e4c1e2a33ab1.png)

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop ![hanging_tendril_active](https://user-images.githubusercontent.com/27739930/164556349-d9066ba9-8cbf-41f0-b6fa-39d416b61c4d.gif)

WHATWEYGVFFHVAJKNWM

**Comment by AViewFromTheTop** [comment]
> ![image](https://user-images.githubusercontent.com/27739930/164560176-e9f1c979-ddc8-4060-86b2-515622e4c553.png) ![image](https://user-images.githubusercontent.com/27739930/164560194-785d57df-340e-473f-b430-e4c1e2a33ab1.png)

The second layer is still blurry imo, I think some of the "gradient" or shading should be removed

**Comment by MerpisMe** [comment]
> The second layer is still blurry imo, I think some of the "gradient" or shading should be removed

i've spent a total of three hours trying to do that but it just doesn't look right

**Comment by AViewFromTheTop** [comment]
> i've spent a total of three hours trying to do that but it just doesn't look right

ok then lets go with it

**Comment by MerpisMe** [comment]
> ok then lets go with it

![image](https://user-images.githubusercontent.com/27739930/164561814-71899f4e-78ba-4f8b-9205-3f12f03a6543.png)
one last try, how's this?

**Comment by BluePhoenixLOL** [comment]
> > ok then lets go with it
> 
> ![image](https://user-images.githubusercontent.com/27739930/164561814-71899f4e-78ba-4f8b-9205-3f12f03a6543.png) one last try, how's this?

yesss

**Comment by MerpisMe** [comment]
![image](https://user-images.githubusercontent.com/27739930/164563054-45525c07-f450-4d2d-a1de-c249d72240c7.png)
e

**Comment by MerpisMe** [comment]
![image](https://user-images.githubusercontent.com/27739930/164563386-13414782-b9c0-4e68-8bdb-6ad517f2ec9e.png)
f

**Comment by BluePhoenixLOL** [comment]
fuck it, lets go back to the old echoer /jk
![image](https://user-images.githubusercontent.com/80720298/164563683-fc471285-3e81-4148-8e7e-805e0945a402.png)

**Comment by MerpisMe** [comment]
> fuck it, lets go back to the old echoer /jk ![image](https://user-images.githubusercontent.com/80720298/164563683-fc471285-3e81-4148-8e7e-805e0945a402.png)

i will find you

**Comment by AViewFromTheTop** [comment]
wow youve got a lot on you hands

**Comment by MerpisMe** [comment]
> wow youve got a lot on your hands

kill me

**Comment by AViewFromTheTop** [comment]
> kill me

i think you should begin with "cause an eathquake," i did that once and california hates me

**Comment by MerpisMe** [comment]
> i did that once and california hates me

elaborate

**Comment by AViewFromTheTop** [comment]
> elaborate

math and science quizzes when the test writer doesn't know anything about math or science

**Comment by MerpisMe** [comment]
> > elaborate
> 
> math and science quizzes when the test writer doesn't know anything about math or science

understood

**Comment by AViewFromTheTop** [comment]
pollen block texture should hopefully be easy

**Comment by MerpisMe** [comment]
> * [ ]  Make pollen block texture

i'm kinda fried atm and i hjave no idea what im doing but um
![image](https://user-images.githubusercontent.com/27739930/164872817-7a90793a-dac8-4874-ade0-676f1ebede5c.png)
candy corn block

**Comment by BluePhoenixLOL** [comment]
> > * [ ]   Make pollen block texture
> 
> i'm kinda fried atm and i hjave no idea what im doing but um ![image](https://user-images.githubusercontent.com/27739930/164872817-7a90793a-dac8-4874-ade0-676f1ebede5c.png) candy corn block

hmm it kinda looks like honeycomb, but i think its good

**Comment by MerpisMe** [comment]
> > > * [ ]    Make pollen block texture
> > 
> > 
> > i'm kinda fried atm and i hjave no idea what im doing but um ![image](https://user-images.githubusercontent.com/27739930/164872817-7a90793a-dac8-4874-ade0-676f1ebede5c.png) candy corn block
> 
> hmm it kinda looks like honeycomb, but i think its good

honeycomb is indirectly made of pollen so im not too phased by that

**Comment by AViewFromTheTop** [comment]
> > hmm it kinda looks like honeycomb, but i think its good
> 
> honeycomb is indirectly made of pollen (?) so im not too phased by that

Nope it’s made by beeswax which has nothing to do with pollen
Regardless, the color scheme is good and shows relation to bees and I like it anyway

**Comment by MerpisMe** [comment]
> > Nope it’s made by beeswax which has nothing to do with pollen

"i'm kinda fried atm" :p

**Comment by AViewFromTheTop** [comment]
> > > Nope it’s made by beeswax which has nothing to do with pollen
> 
> "i'm kinda fried atm" :p

KFC rats in a nutshell

**Comment by AViewFromTheTop** [comment]
wow merp that's a really suspicious shopping list you've got there

**Comment by BluePhoenixLOL** [comment]
![image](https://user-images.githubusercontent.com/80720298/164950372-0c1a2bec-c8e7-49c1-9657-7705e3000bd5.png)
NOOOOOOOOOOOOOO

**Comment by MerpisMe** [comment]
> wow merp that's a really suspicious shopping list you've got there

oop that shouldn't have made it onto here oooooopsie daisies

**Comment by BluePhoenixLOL** [comment]
![image](https://user-images.githubusercontent.com/80720298/164950401-ef3594bf-d28e-44b5-a447-0357d28abf8b.png)
NOOOOOOOOOOOOOOOOOOOO

**Comment by AViewFromTheTop** [comment]
> > wow merp that's a really suspicious shopping list you've got there
> 
> oop that shouldn't have made it onto here oooooopsie daisies

it looks you you're going to hold someone hostage, why is that?

**Comment by AViewFromTheTop** [comment]
> wow merp that's a really sus

**Comment by MerpisMe** [comment]
> it looks you you're going to hold someone hostage, why is that?

overspeculation obviously

**Comment by MerpisMe** [comment]
> * [ ]  Make unique sounds for breaking and walking on lilypads (may need help from @AViewFromTheTop to register this)

@AViewFromTheTop hi
for now it can just use the same sound as placing it for all of them, i just have no idea how to override a vanilla block's sounds

**Comment by AViewFromTheTop** [comment]
@MerpisMe updated

**Comment by MerpisMe** [comment]
![image](https://user-images.githubusercontent.com/27739930/166123450-f54b06b0-faec-4eca-8170-4d3887ebd015.png)
heresy

**Comment by AViewFromTheTop** [comment]
> ![image](https://user-images.githubusercontent.com/27739930/166123450-f54b06b0-faec-4eca-8170-4d3887ebd015.png) heresy

no i am correct

**Comment by MerpisMe** [comment]
> no i am correct

![merp_uwu](https://user-images.githubusercontent.com/27739930/166123495-850fb288-2845-48b2-a0d3-d8a96946fc95.png)

**Comment by AViewFromTheTop** [comment]
LOL

**Comment by AViewFromTheTop** [comment]
why was my comment deleted

**Comment by MerpisMe** [comment]
> why was my comment deleted

wasnt me :trollface:

**Comment by AViewFromTheTop** [comment]
> wasnt me :trollface:

you are censorship
why

**Comment by MerpisMe** [comment]
> you are censorship 
> why

idk 
i'm in a weird mood

**Comment by AViewFromTheTop** [comment]
> idk i'm in a weird mood

same, for the last 5 years

**Comment by MerpisMe** [comment]
> same, for the last 5 years

yeah but its not like a good mood, it's one that would make you not want to interact with a person who is in that mood

**Comment by AViewFromTheTop** [comment]
> > same, for the last 5 years
> 
> yeah but its not like a good mood, it's one that would make you not want to interact with a person who is in that mood

oh

**Comment by MerpisMe** [comment]
> oh

yeah it's _that_ mood

**Comment by MerpisMe** [comment]
> * [ ]  Make unique block sounds for shelf fungi (and maybe use these for placing normal mushrooms as well if we can figure out how to override vanilla block sounds)

@AViewFromTheTop pplplpllplpppll (do you know how to do this)

**Comment by MerpisMe** [comment]
> I don't 
> And not every single block needs unique sounds, mushrooms are the last things in existence that need unique sounds

nether fungi have unique sounds though :(

also, i've never liked that the mushroom blocks make wood sounds while the mushroom plants make grass sounds.

**Comment by MerpisMe** [comment]
> > I don't
> > And not every single block needs unique sounds, mushrooms are the last things in existence that need unique sounds
> 
> nether fungi have unique sounds though :(
> 
> also, i've never liked that the mushroom blocks make wood sounds while the mushroom plants make grass sounds.

@AViewFromTheTop https://github.com/Trainguy9512/trainguys-block-sound-refresher 
bam, just remembered that this mod exists that overrides the vanilla block sounds, would be worth taking a look at. seems like it just mixins the default block class and simple adds new SoundEvents to existing blocks

**Comment by MerpisMe** [comment]
> * [ ]  Make unique warden death animation (and maybe get it to work in-game???)

@AViewFromTheTop owo
![5A650989-2C3C-4450-BA14-DAE7543BEC60](https://user-images.githubusercontent.com/27739930/166976984-a6fd2239-07f2-471c-8a11-e3d8ce2c7bc3.gif)

**Comment by AViewFromTheTop** [comment]
> > * [ ]   Make unique warden death animation (and maybe get it to work in-game???)
> 
> @AViewFromTheTop ![5A650989-2C3C-4450-BA14-DAE7543BEC60](https://user-images.githubusercontent.com/27739930/166976984-a6fd2239-07f2-471c-8a11-e3d8ce2c7bc3.gif)

pogger

**Comment by BluePhoenixLOL** [comment]
ok so

**Comment by BluePhoenixLOL** [comment]
convert to the new 1.19 system (AAAAAAAAAAAAAAAAAAA) and mixin to WardenAnimations And WardenEntityModel

**Comment by AViewFromTheTop** [comment]
@MerpisMe oh BTW, the animation will have to fit in a 20-tick span, or 1 second, in order to see the entire thing. We _could possibly_ make a mixin to get around this, but... eh. idk.

**Comment by MerpisMe** [comment]
i'm tired of trying
cya

**Comment by Osmiooo** [comment]
> i'm tired of trying cya

What's happening? Why did u leave?

**Comment by MerpisMe** [comment]
> > i'm tired of trying cya
> 
> What's happening? Why did u leave the discord?

@Soro335

**Comment by Osmiooo** [comment]
> > > i'm tired of trying cya
> > 
> > 
> > What's happening? Why did u leave the discord?
> 
> @Soro335

What did he do

**Comment by Soro335** [comment]
> > > i'm tired of trying cya
> > 
> > 
> > What's happening? Why did u leave the discord?
> 
> @Soro335

I don't understand why you are afraid of a discord release that 10 people will download, we just need feedback

**Comment by Osmiooo** [comment]
> > > > i'm tired of trying cya
> > > 
> > > 
> > > What's happening? Why did u leave the discord?
> > 
> > 
> > @Soro335
> 
> I don't understand why you are afraid of a discord release that 10 people will download, we just need feedback

Soro. First, we're 1k, I know everyone won't download but way more than 10. Then, the mod isn't finished at all. And don't annoy merp, she doesn't want to release it you can understand it, she's right.

**Comment by MerpisMe** [comment]
> I don't understand why you are afraid of a discord release that 10 people will download, we just need feedback

because you're rushing the mod's release even after i've told you several times that we need to take it slow. last time we started releasing test builds we kept getting people begging and begging for the next one and that was really stressful.
but i left because you were being a fucking dick to me after i'd already apologized for lashing out against you and explained why i did. you need to get your head out of your ass and read into the context. i have been so stressed out lately that i am closer than ever to losing everything, and the fact that you were not taking the situation even the slightest bit seriously pissed me off. i said "you're not listening to me" and you reply to it with "you're right, because i'm reading" like that's okay. what the fuck do you think was going to happen??? i am clearly not in any mood to joke around like that. grow up.
i'm done.

**Comment by Soro335** [comment]
Okay, I'm taking a week off, peace. =))

**Comment by MerpisMe** [comment]
k

**Comment by MerpisMe** [comment]
> > Okay, I'm taking a week off, peace. =))
> 
> wait what

yeah i dunno either, guess he just wanted to move the focus to himself even though he's the offender in this situation lol

**Comment by BluePhoenixLOL** [comment]
![image](https://user-images.githubusercontent.com/80720298/167468952-e650a561-7bd8-480b-b1be-034009613b1c.png)

**Comment by BluePhoenixLOL** [comment]
AAAAAAAAAAA

**Comment by BluePhoenixLOL** [comment]
please tell me this is a really late april fools joke

**Comment by MerpisMe** [comment]
oh hey btw @AViewFromTheTop is the new milkweed texture good

**Comment by BluePhoenixLOL** [comment]
> @MerpisMe new texture, Sandy Dirt hopefully the last texture needed before release i think we should put the new milkweed on hold honestly

lmao you forgot prickly pears and tumbleweeds

**Comment by BluePhoenixLOL** [comment]
oh wait you sent that like a month ago

**Comment by Xfrtrex** [comment]
so uh do we close this or are you gonna update it

**Comment by MerpisMe** [comment]
> so uh do we close this or are you gonna update it

no dont close it. it's for when i'm on a break or can't be working on the mod for an extended period of time

**Comment by MerpisMe** [comment]
@Treetrain1 @Xfrtrex @AViewFromTheTop can you guys please start using this again for a little bit
i might not be as active since i have to be tending to my dog (for those who aren't aware, he's got really bad diarrhea and it's to the point where, if he doesn't get better within the month, we'll have to put him down)
obviously that doesn't necessarily mean i'll always be unavailable, but i'll be less active than usual during certain points in time
thanks

**Comment by AViewFromTheTop** [comment]
> @Treetrain1 @Xfrtrex @AViewFromTheTop can you guys please start using this again for a little bit
> i might not be as active since i have to be tending to my dog (for those who aren't aware, he's got really bad diarrhea and it's to the point where, if he doesn't get better within the next month or so, we'll have to put him down)
> obviously that doesn't necessarily mean i'll always be unavailable, but i'll be less active than usual during certain points in time
> thanks

Same here- have you tried switching him to raw food? My gal is still alive purely because of it. It takes a while to switch onto it, but it may be worth it. Beware, however, the cost is… up there.

**Comment by MerpisMe** [comment]
> Same here- have you tried switching him to raw food? My gal is still alive purely because of it. It takes a while to switch onto it, but it may be worth it. Beware, however, the cost is… up there.

no.. it's nothing he's eating. it's been sudden explosive uncontrollable diarrhea. got to the point where it was just bile and he'd still be unable to control it. he's also 12 and hasn't ever shown any allergies to stuff like that before. it came out of nowhere, we didn't change anything in his diet at all prior to it.

the poor thing has to sleep in the bathroom with the floor covered in pads, in the mornings he's completely covered in it and we have to bathe him

i don't really know at this point. we've taken him to the vet, they did a bit of screening and it's not a blockage in his digestive tract, it's not anything he's eating, and it wasn't dehydration. we can't afford any more screening so we're trying to just do the stuff they told us to do. the weirdest part of it all is that he acts COMPLETELY normal up until he has to go, and then he's trying his best to not completely explode.

**Comment by AViewFromTheTop** [comment]
Yikes… I mean… I’ve seen it in each puppy I’ve owned (aside from my rat thing for some reason) but elderly dogs…
I’m sorry to hear that… I hope all goes well…

**Comment by MerpisMe** [comment]
> Yikes… I mean… I’ve seen it in each puppy I’ve owned (aside from my rat thing for some reason) but elderly dogs… I’m sorry to hear that… I hope all goes well…

i do too. i appreciate it.
i've had him for so long that i honestly don't know what i'd do without him. he's been a pretty substantial reason why i'm still here on numerous occasions.

**Comment by MerpisMe** [comment]
> he's been a pretty substantial reason why i'm still here on numerous occasions.

i really hate saying stuff like this because i know it doesnt add anything to the conversation, but it's true

**Comment by AViewFromTheTop** [comment]
> > Yikes… I mean… I’ve seen it in each puppy I’ve owned (aside from my rat thing for some reason) but elderly dogs… I’m sorry to hear that… I hope all goes well…
> 
> i do too. i appreciate it. i've had him for so long that i honestly don't know what i'd do without him. he's been a pretty substantial reason why i'm still here on numerous occasions.

Same here, with my old lass Julie. She was bleeding out her legs the day before she had to get out down, we did our best to keep her last days calm. So many terrible days of young rage, sadness, and blasphemy were eased by her, she really was the best of them all. She had a life of her own, could run the house by herself if she wanted. Those days all do eventually come, regardless of the cause. I had to tell myself that it’ll only result in positives- maybe I’ll make new memories in the future! Maybe I’ll be pushed to do something even better with myself. Even though none was true, I hope you can find at least one positive. You may have to dig deep- deep into yourself, your future and your past, but you never know. Life can’t be predicted with the flip of a coin, there will be a positive out in that open field one day.

**Comment by Xfrtrex** [comment]
> @Treetrain1 @Xfrtrex @AViewFromTheTop can you guys please start using this again for a little bit i might not be as active since i have to be tending to my dog (for those who aren't aware, he's got really bad diarrhea and it's to the point where, if he doesn't get better within the next month or so, we'll have to put him down) obviously that doesn't necessarily mean i'll always be unavailable, but i'll be less active than usual during certain points in time thanks

:( 
also wdym using it? like showing tasks or something?

**Comment by AViewFromTheTop** [comment]
And I don’t mean waiting for the positive thing to come, I mean tricking yourself into believing it. That’s the best way to guarantee something good will actually happen, it’s the greatest motivator.

**Comment by MerpisMe** [comment]
> And I don’t mean waiting for the positive thing to come, I mean tricking yourself into believing it. That’s the best way to guarantee something good will actually happen, it’s the greatest motivator.

not sure how i feel about the idea of tricking myself into believing that my dog potentially facing certain death very soon is a positive thing

**Comment by AViewFromTheTop** [comment]
@MerpisMe forgor to update you that this issue has been updated
two things

**Comment by AViewFromTheTop** [comment]
Closing since youve left
